<?php

namespace Drupal\breadcrumb_item\Plugin\Block;

use Drupal\Core\Block\BlockBase;
use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Breadcrumb\BreadcrumbBuilderInterface;

/**
 * Provides a custom block breadcrumb item.
 *
 * @Block(
 *   id = "breadcrumb_item_block",
 *   admin_label = @Translation("Breadcrumb Item"),
 *
 * )
 */
class BreadcrumbItemBlock extends BlockBase {

    /**
     * {@inheritdoc}
     */
    public function build() {
        $title = "";
        
        // Get breadcrumb generated by the module easy_breadcrumb
        
        // Get the x item and retrieve the title


        return array(
            '#title' => $title,
            '#cache' => array(
                'contexts' => array('url.path'),
            )
        );
    }

}
